apiVersion: apps/v1
kind: Deployment
metadata:
  name: cric-app-1
  namespace: default
  annotations:
    autopilot.gke.io/resource-adjustment: >-
      {"input":{"containers":[{"name":"real-time-crick-score-app-1"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"real-time-crick-score-app-1"}]},"modified":true}
    autopilot.gke.io/warden-version: 31.23.0-gke.8
  labels:
    app: cric-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cric-app-1
      app.kubernetes.io/managed-by: gcp-cloud-build-deploy
      app.kubernetes.io/name: cric-app-1
      app.kubernetes.io/version: a171194a0210273825d13ff7e583f63e6077ec7a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cric-app-1
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: cric-app-1
        app.kubernetes.io/version: a171194a0210273825d13ff7e583f63e6077ec7a
    spec:
      containers:
        - name: real-time-crick-score-app-1
          image: gcr.io/qwiklabs-gcp-00-3df61adb79dc/github.com/mathankrish/real-time-crick-score-app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cric-app-1-hpa-g3z0
  namespace: default
  labels:
    app: cric-app-1
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cric-app-1

---

apiVersion: v1
kind: Service
metadata:
  name: cric-app-1-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: cric-app-1
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.227.162
  clusterIPs:
    - 34.118.227.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32747
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cric-app-1
    app.kubernetes.io/managed-by: cloud-console
  sessionAffinity: None
  type: LoadBalancer
